using System.Security.Cryptography;
using System.Text.Json;
using OpenLIMS.Contracts.Toy;

namespace OpenLIMS.Modules.Toy;

/// <summary>
/// OD-034@1.0.0: Two-level conclusion hierarchy for toy testing.
/// ITEM_CONFORMITY approved by technical director; TESTED_SCOPE_CONFORMITY
/// approved by authorized signatory with re-authentication signature.
/// WHOLE_PRODUCT_COMPLIANCE is permanently prohibited.
/// </summary>
internal static class ToyConclusionDomain
{
    /// <summary>
    /// Validate and prepare ITEM_CONFORMITY conclusion draft.
    /// Single test item conformity to a single requirement version.
    /// </summary>
    public static ItemConformityConclusionDraft ValidateItemConformityRequest(
        CreateItemConformityConclusionRequest? request)
    {
        if (request is null)
            throw new ToyDomainException(ToyErrorCodes.ValidationFailed);

        if (string.IsNullOrWhiteSpace(request.AdoptedResultRef) ||
            request.AdoptedResultVersion < 1 ||
            string.IsNullOrWhiteSpace(request.RequirementRef) ||
            request.RequirementVersion < 1 ||
            string.IsNullOrWhiteSpace(request.RuleSetVersion))
        {
            throw new ToyDomainException(ToyErrorCodes.ConclusionEvidenceIncomplete);
        }

        if (!string.Equals(
            request.RuleSetVersion,
            ToyConclusionContract.RuleSetVersion,
            StringComparison.Ordinal))
        {
            throw new ToyDomainException(ToyErrorCodes.ConclusionPolicyUnknown);
        }

        // OD-034: Conclusion statement must be generated by system fixed template.
        // Caller-supplied wording is rejected.
        if (!string.IsNullOrWhiteSpace(request.CustomStatement))
        {
            throw new ToyDomainException(ToyErrorCodes.ConclusionPolicyUnknown);
        }

        var statement = GenerateItemConformityStatement(
            request.AdoptedResultRef,
            request.AdoptedResultVersion,
            request.RequirementRef,
            request.RequirementVersion);

        return new ItemConformityConclusionDraft(
            request.AdoptedResultRef,
            request.AdoptedResultVersion,
            request.RequirementRef,
            request.RequirementVersion,
            request.RuleSetVersion,
            statement,
            CalculateItemContentHash(request));
    }

    /// <summary>
    /// Validate and prepare TESTED_SCOPE_CONFORMITY conclusion draft.
    /// Multi-TestUnit conformity with mandatory uncovered scope disclosure.
    /// </summary>
    public static TestedScopeConformityConclusionDraft ValidateTestedScopeConformityRequest(
        CreateTestedScopeConformityConclusionRequest? request)
    {
        if (request is null)
            throw new ToyDomainException(ToyErrorCodes.ValidationFailed);

        if (string.IsNullOrWhiteSpace(request.ProductRef) ||
            request.ProductVersion < 1 ||
            string.IsNullOrWhiteSpace(request.TestUnitPlanRef) ||
            request.TestUnitPlanVersion < 1 ||
            string.IsNullOrWhiteSpace(request.RuleSetVersion))
        {
            throw new ToyDomainException(ToyErrorCodes.ConclusionEvidenceIncomplete);
        }

        if (!string.Equals(
            request.RuleSetVersion,
            ToyConclusionContract.RuleSetVersion,
            StringComparison.Ordinal))
        {
            throw new ToyDomainException(ToyErrorCodes.ConclusionPolicyUnknown);
        }

        // OD-034: TestUnit evidence must be complete with all version references
        if (request.TestUnits is null || request.TestUnits.Count == 0)
        {
            throw new ToyDomainException(ToyErrorCodes.ConclusionEvidenceIncomplete);
        }

        foreach (var testUnit in request.TestUnits)
        {
            if (string.IsNullOrWhiteSpace(testUnit.TestUnitId) ||
                string.IsNullOrWhiteSpace(testUnit.PhysicalObjectRef) ||
                testUnit.PhysicalObjectVersion < 1 ||
                string.IsNullOrWhiteSpace(testUnit.HazardDomainRef) ||
                testUnit.HazardDomainVersion < 1 ||
                string.IsNullOrWhiteSpace(testUnit.AdoptedResultRef) ||
                testUnit.AdoptedResultVersion < 1 ||
                string.IsNullOrWhiteSpace(testUnit.ResultProvenanceGraphRef) ||
                testUnit.ResultProvenanceGraphVersion < 1)
            {
                throw new ToyDomainException(ToyErrorCodes.ConclusionEvidenceIncomplete);
            }

            if (string.IsNullOrWhiteSpace(testUnit.CoverageDecisionRef) ||
                testUnit.CoverageDecisionVersion < 1)
            {
                throw new ToyDomainException(ToyErrorCodes.ConclusionEvidenceIncomplete);
            }
        }

        // OD-034: Uncovered scopes disclosure is MANDATORY. Cannot be null or empty.
        // Empty array is NOT treated as "fully covered" — that's a deliberate rejection.
        if (request.UncoveredScopes is null || request.UncoveredScopes.Count == 0)
        {
            throw new ToyDomainException(ToyErrorCodes.ConclusionEvidenceIncomplete);
        }

        foreach (var uncovered in request.UncoveredScopes)
        {
            if (string.IsNullOrWhiteSpace(uncovered.Scope) ||
                string.IsNullOrWhiteSpace(uncovered.Reason) ||
                !IsValidUncoveredReason(uncovered.Reason))
            {
                throw new ToyDomainException(ToyErrorCodes.ConclusionEvidenceIncomplete);
            }
        }

        // OD-034: Caller-supplied wording is rejected
        if (!string.IsNullOrWhiteSpace(request.CustomStatement))
        {
            throw new ToyDomainException(ToyErrorCodes.ConclusionPolicyUnknown);
        }

        // OD-034: Reject any request for whole-product comprehensive compliance
        if (request.IsFictitiousWholeItemConclusion == true)
        {
            throw new ToyDomainException(ToyErrorCodes.FictitiousWholeItemConclusion);
        }

        if (request.ExternalReferences is not null && request.ExternalReferences.Any(reference =>
            reference is null ||
            string.IsNullOrWhiteSpace(reference.Issuer) ||
            string.IsNullOrWhiteSpace(reference.Reference) ||
            string.IsNullOrWhiteSpace(reference.StatedScope) ||
            !reference.NotPartOfThisConclusion))
        {
            throw new ToyDomainException(ToyErrorCodes.ConclusionPolicyUnknown);
        }

        if (request.ReauthenticationRef is null ||
            string.IsNullOrWhiteSpace(request.ReauthenticationRef.Id) ||
            request.ReauthenticationRef.Version < 1 ||
            string.IsNullOrWhiteSpace(request.SigningIntent) ||
            string.IsNullOrWhiteSpace(request.SignedContentHash))
        {
            throw new ToyDomainException(ToyErrorCodes.ConclusionSignatureInvalid);
        }

        var contentHash = CalculateTestedScopeContentHash(request);
        if (!string.Equals(
            contentHash,
            request.SignedContentHash.Trim(),
            StringComparison.OrdinalIgnoreCase))
        {
            throw new ToyDomainException(ToyErrorCodes.ConclusionSignatureInvalid);
        }

        var covered = request.TestUnits
            .Select(tu => tu.HazardDomainRef)
            .Distinct(StringComparer.Ordinal)
            .OrderBy(hd => hd, StringComparer.Ordinal)
            .ToArray();

        var requirements = request.TestUnits
            .SelectMany(tu => tu.RequirementRefs ?? Array.Empty<string>())
            .Distinct(StringComparer.Ordinal)
            .OrderBy(r => r, StringComparer.Ordinal)
            .ToArray();

        var statement = GenerateTestedScopeConformityStatement(
            request.TestUnits.Count,
            covered,
            requirements,
            request.UncoveredScopes);

        return new TestedScopeConformityConclusionDraft(
            request.ProductRef,
            request.ProductVersion,
            request.TestUnitPlanRef,
            request.TestUnitPlanVersion,
            request.TestUnits.ToArray(),
            covered,
            request.UncoveredScopes.ToArray(),
            request.RuleSetVersion,
            statement,
            request.ExternalReferences?.ToArray(),
            request.ReauthenticationRef,
            request.SigningIntent.Trim(),
            contentHash);
    }

    /// <summary>
    /// Validate Separation of Duty: conclusion approver must not be the recorder
    /// of any adoptedResult referenced in the conclusion.
    /// </summary>
    public static void ValidateSeparationOfDuty(
        string approverId,
        IReadOnlyList<string> resultRecorderIds)
    {
        if (resultRecorderIds is null || resultRecorderIds.Count == 0 ||
            resultRecorderIds.Any(string.IsNullOrWhiteSpace))
        {
            throw new ToyDomainException(ToyErrorCodes.ConclusionEvidenceUnknown);
        }

        if (resultRecorderIds.Any(recorderId =>
            string.Equals(recorderId, approverId, StringComparison.Ordinal)))
        {
            throw new ToyDomainException(ToyErrorCodes.ConclusionSodViolation);
        }
    }

    public static string CalculateTestedScopeContentHash(
        CreateTestedScopeConformityConclusionRequest request)
    {
        ArgumentNullException.ThrowIfNull(request);
        var canonical = new
        {
            request.RuleSetVersion,
            request.ProductRef,
            request.ProductVersion,
            request.TestUnitPlanRef,
            request.TestUnitPlanVersion,
            TestUnits = (request.TestUnits ?? [])
                .OrderBy(unit => unit.TestUnitId, StringComparer.Ordinal)
                .Select(unit => new
                {
                    unit.TestUnitId,
                    unit.PhysicalObjectRef,
                    unit.PhysicalObjectVersion,
                    unit.HazardDomainRef,
                    unit.HazardDomainVersion,
                    unit.AdoptedResultRef,
                    unit.AdoptedResultVersion,
                    unit.ResultProvenanceGraphRef,
                    unit.ResultProvenanceGraphVersion,
                    unit.CoverageDecisionRef,
                    unit.CoverageDecisionVersion,
                    RequirementRefs = (unit.RequirementRefs ?? [])
                        .Order(StringComparer.Ordinal)
                        .ToArray()
                })
                .ToArray(),
            UncoveredScopes = (request.UncoveredScopes ?? [])
                .OrderBy(scope => scope.Scope, StringComparer.Ordinal)
                .ThenBy(scope => scope.Reason, StringComparer.Ordinal)
                .ThenBy(scope => scope.Detail, StringComparer.Ordinal)
                .ToArray(),
            ExternalReferences = (request.ExternalReferences ?? [])
                .OrderBy(reference => reference.Issuer, StringComparer.Ordinal)
                .ThenBy(reference => reference.Reference, StringComparer.Ordinal)
                .ThenBy(reference => reference.StatedScope, StringComparer.Ordinal)
                .ToArray(),
            request.CustomStatement,
            request.IsFictitiousWholeItemConclusion,
            ReauthenticationRef = request.ReauthenticationRef is null
                ? null
                : new { request.ReauthenticationRef.Id, request.ReauthenticationRef.Version },
            SigningIntent = request.SigningIntent?.Trim()
        };
        return Hash(canonical);
    }

    private static string CalculateItemContentHash(CreateItemConformityConclusionRequest request) =>
        Hash(new
        {
            request.RuleSetVersion,
            request.AdoptedResultRef,
            request.AdoptedResultVersion,
            request.RequirementRef,
            request.RequirementVersion
        });

    private static string Hash<T>(T value) =>
        Convert.ToHexStringLower(SHA256.HashData(JsonSerializer.SerializeToUtf8Bytes(value)));

    /// <summary>
    /// Generate fixed-template statement for ITEM_CONFORMITY.
    /// OD-034: System-controlled wording, no caller customization.
    /// </summary>
    private static string GenerateItemConformityStatement(
        string adoptedResultRef,
        long adoptedResultVersion,
        string requirementRef,
        long requirementVersion)
    {
        return $"检测项目 {adoptedResultRef}@{adoptedResultVersion} 符合要求 {requirementRef}@{requirementVersion}";
    }

    /// <summary>
    /// Generate fixed-template statement for TESTED_SCOPE_CONFORMITY.
    /// OD-034: Must include mandatory uncovered scopes section, cannot be omitted.
    /// </summary>
    private static string GenerateTestedScopeConformityStatement(
        int testUnitCount,
        string[] coveredHazardDomains,
        string[] requirements,
        IReadOnlyList<UncoveredScopeInput> uncoveredScopes)
    {
        var coveredText = string.Join("、", coveredHazardDomains);
        var requirementsText = requirements.Length > 0
            ? string.Join("、", requirements)
            : "相关要求";

        var uncoveredLines = uncoveredScopes
            .Select(u => $"  - {u.Scope}：{GetReasonText(u.Reason)}（{u.Detail}）")
            .ToArray();
        var uncoveredText = string.Join(Environment.NewLine, uncoveredLines);

        // OD-034: Fixed template with mandatory uncovered section
        return $"""
            所检 {testUnitCount} 个 TestUnit 就下列已测危险域符合 {requirementsText}：
            已测危险域：{coveredText}

            未覆盖项（强制披露）：
            {uncoveredText}
            """;
    }

    private static string GetReasonText(string reason) => reason switch
    {
        "NOT_TESTED" => "未检测",
        "UNKNOWN" => "适用性未知",
        "NOT_APPLICABLE" => "不适用",
        _ => reason
    };

    private static bool IsValidUncoveredReason(string reason) =>
        reason is "NOT_TESTED" or "UNKNOWN" or "NOT_APPLICABLE";
}

internal sealed record ItemConformityConclusionDraft(
    string AdoptedResultRef,
    long AdoptedResultVersion,
    string RequirementRef,
    long RequirementVersion,
    string RuleSetVersion,
    string Statement,
    string ContentHash);

internal sealed record TestedScopeConformityConclusionDraft(
    string ProductRef,
    long ProductVersion,
    string TestUnitPlanRef,
    long TestUnitPlanVersion,
    TestUnitEvidenceInput[] TestUnits,
    string[] CoveredHazardDomains,
    UncoveredScopeInput[] UncoveredScopes,
    string RuleSetVersion,
    string Statement,
    ExternalReferenceInput[]? ExternalReferences,
    ToyVersionedReference ReauthenticationRef,
    string SigningIntent,
    string ContentHash);
