<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>OpenLIMS.Modules.Qc</AssemblyName>
    <RootNamespace>OpenLIMS.Modules.Qc</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Npgsql" />
    <ProjectReference Include="../../../../contracts/qc/OpenLIMS.Contracts.Qc/OpenLIMS.Contracts.Qc.csproj" />
    <ProjectReference Include="../../../../contracts/batch/OpenLIMS.Contracts.Batch/OpenLIMS.Contracts.Batch.csproj" />
    <ProjectReference Include="../../../../contracts/platform/OpenLIMS.Contracts.Platform/OpenLIMS.Contracts.Platform.csproj" />
    <ProjectReference Include="../../../building-blocks/OpenLIMS.BuildingBlocks.Platform/OpenLIMS.BuildingBlocks.Platform.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="OpenLIMS.Qc.UnitTests" />
    <InternalsVisibleTo Include="OpenLIMS.Qc.IntegrationTests" />
    <InternalsVisibleTo Include="OpenLIMS.Qc.ContractTests" />
  </ItemGroup>
</Project>
