<Project Sdk="Microsoft.NET.Sdk.Worker">
  <PropertyGroup>
    <AssemblyName>OpenLIMS.Worker</AssemblyName>
    <RootNamespace>OpenLIMS.Worker</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="OpenTelemetry.Extensions.Hosting" />
    <ProjectReference Include="../../../building-blocks/OpenLIMS.BuildingBlocks.Platform/OpenLIMS.BuildingBlocks.Platform.csproj" />
    <ProjectReference Include="../../../../contracts/platform/OpenLIMS.Contracts.Platform/OpenLIMS.Contracts.Platform.csproj" />
    <ProjectReference Include="../../../modules/receiving/OpenLIMS.Modules.Receiving/OpenLIMS.Modules.Receiving.csproj" />
    <ProjectReference Include="../../../modules/labeling/OpenLIMS.Modules.Labeling/OpenLIMS.Modules.Labeling.csproj" />
    <ProjectReference Include="../../../modules/scope/OpenLIMS.Modules.Scope/OpenLIMS.Modules.Scope.csproj" />
  </ItemGroup>
</Project>
