<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>OpenLIMS.Result.ContractTests</AssemblyName>
    <RootNamespace>OpenLIMS.Result.ContractTests</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <ProjectReference Include="../../../../src/modules/result/OpenLIMS.Modules.Result/OpenLIMS.Modules.Result.csproj" />
    <ProjectReference Include="../../../../contracts/result/OpenLIMS.Contracts.Result/OpenLIMS.Contracts.Result.csproj" />
    <ProjectReference Include="../../../../src/host/api/OpenLIMS.Api/OpenLIMS.Api.csproj" />
  </ItemGroup>
</Project>
