<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>OpenLIMS.Report.ContractTests</AssemblyName>
    <RootNamespace>OpenLIMS.Report.ContractTests</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <ProjectReference Include="../../../../src/modules/report/OpenLIMS.Modules.Report/OpenLIMS.Modules.Report.csproj" />
    <ProjectReference Include="../../../../contracts/report/OpenLIMS.Contracts.Report/OpenLIMS.Contracts.Report.csproj" />
    <ProjectReference Include="../../../../src/host/api/OpenLIMS.Api/OpenLIMS.Api.csproj" />
  </ItemGroup>
</Project>
