<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>OpenLIMS.BuildingBlocks.Platform</AssemblyName>
    <RootNamespace>OpenLIMS.BuildingBlocks.Platform</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="AWSSDK.S3" />
    <PackageReference Include="Npgsql" />
    <ProjectReference Include="../../../contracts/platform/OpenLIMS.Contracts.Platform/OpenLIMS.Contracts.Platform.csproj" />
  </ItemGroup>
</Project>
