<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>OpenLIMS.Report.UnitTests</AssemblyName>
    <RootNamespace>OpenLIMS.Report.UnitTests</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <ProjectReference Include="../../../../src/modules/report/OpenLIMS.Modules.Report/OpenLIMS.Modules.Report.csproj" />
    <ProjectReference Include="../../../../contracts/report/OpenLIMS.Contracts.Report/OpenLIMS.Contracts.Report.csproj" />
    <ProjectReference Include="../../../../contracts/platform/OpenLIMS.Contracts.Platform/OpenLIMS.Contracts.Platform.csproj" />
  </ItemGroup>
</Project>
