<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>OpenLIMS.Qc.IntegrationTests</AssemblyName>
    <RootNamespace>OpenLIMS.Qc.IntegrationTests</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="Npgsql" />
    <ProjectReference Include="../../../../src/modules/qc/OpenLIMS.Modules.Qc/OpenLIMS.Modules.Qc.csproj" />
    <ProjectReference Include="../../../../contracts/qc/OpenLIMS.Contracts.Qc/OpenLIMS.Contracts.Qc.csproj" />
    <ProjectReference Include="../../../../contracts/batch/OpenLIMS.Contracts.Batch/OpenLIMS.Contracts.Batch.csproj" />
    <ProjectReference Include="../../../../src/building-blocks/OpenLIMS.BuildingBlocks.Platform/OpenLIMS.BuildingBlocks.Platform.csproj" />
    <ProjectReference Include="../../../../contracts/platform/OpenLIMS.Contracts.Platform/OpenLIMS.Contracts.Platform.csproj" />
  </ItemGroup>
</Project>
